name: LeagueStatTracker_Project

services:
- environment_slug: python
  github:
    branch: main
    deploy_on_push: true
    repo: KenthonyGarcia/LeagueStatTracker_Project
  name: LeagueStatTracker_Project
